config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints(host: /^www\./i) do
    get '(*any)', to: redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host.sub!(/^www\./i, '') }.to_s
    }
  end

  match "/404" => "errors#not_found", via: [:all]

  root 'grid#index'
  post '/contact' => 'contact#validate_and_send', defaults: { format: :json }, as: 'contact_send'
  get 'case-study(/:slug)' => 'case_studies#index', as: 'case_study'

  #get '/careers' => 'careers#listing', via: [:all]
  get '/lets-talk' => 'lets_talk#listing', via: [:all]
  get '/case-studies' => 'case_studies#listing', via: [:all]
  get '/agency' => 'agency#listing', via: [:all]
  get '/what-we-do' => 'what_we_do#listing', via: [:all]
  get '/who-we-are' => 'who_we_are#listing', via: [:all]


  namespace :admin do
    get  '/' => 'dashboard#index', as: 'dashboard'
    get  '/credentials-test' => 'credentials_test#index', as: 'credentials_test'

    get  '/list' => 'list#index', as: 'list'
    get  '/list/add_page/:page_number' => 'list#add_page'

    get  '/grid' => 'grid#index', as: 'grid'
    get  '/grid/add_page/:page_number' => 'grid#add_page'

    resources :images, only: [:edit, :update, :destroy] do
      new do
        get ':position' => 'images#new', as: ''
      end
      collection do
        post ':position' => 'images#create', as: ''
      end
      member do
        get 'update_position/:position' => 'images#update_position', as: 'reposition'
      end
    end

    resources :case_studies, only: [:edit, :update, :destroy] do
      new do
        get ':style/:position' => 'case_studies#new', as: ''
      end
      collection do
        post ':style/:position' => 'case_studies#create', as: ''
      end
      member do
        get 'update_position/:position' => 'case_studies#update_position', as: 'reposition'
      end
    end

    get 'shots' => 'shots#index'
    get 'shots/status/:id' => 'shots#change_status', as: 'shot_status'

    get '/tweets/add/:position' => 'tweets#add', as: 'tweet_add'
    get '/tweets/remove/:position' => 'tweets#remove', as: 'tweet_remove'
    get '/tweets/update_position/:position/:new_position' => 'tweets#update_position', as: 'tweet_reposition'

    get '/facts/add/:type/:position' => 'facts#add', as: 'fact_add'
    get '/facts/remove/:position' => 'facts#remove', as: 'fact_remove'

    get  '/login'   => 'sessions#new'
    post '/login'   => 'sessions#create'
    get  '/logout'  => 'sessions#destroy'

  end
end

app/controllers/admin/grid_controller.rb
module Admin
  class GridController < SharedViewController

    def add_item_to_page(position, item, page)
      page[position] = item
      page
    end

  end
end

app/controllers/grid_controller.rb
class GridController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    @debug = params[:debug].nil? ? false : true;
    @starting_position = params[:start].nil? ? 0 : params[:start].to_i.not_negative
    @items = []

    reset_fill_pointers
    prepare_items

    if params[:start].nil?
      respond_to :html
    else
      respond_to :js
    end
  end

  private

  def count_grid_items(grid_items)
    grid_items.size + grid_items.count { |i| i.gridable_type.eql? 'CaseStudy' }
  end

  def reset_fill_pointers
    session[:last_video] = session[:last_shot] = Time.now.utc.to_i if @starting_position == 0
  end

  # def prepare_items
  #   grid_items = fetch_grid_items
  #   fill_items = fetch_fill_items(grid_items.size)
  #   @total_items = grid_items.size + fill_items.count
  #   populate_items(grid_items, fill_items)
  # end

   def prepare_items
    grid_items = fetch_grid_items
    grid_items_count = count_grid_items(grid_items)
    fill_items = fetch_fill_items(grid_items_count)
    @total_items = grid_items_count + fill_items.count
    populate_items(grid_items, fill_items)
   end

  def populate_items(grid_items, fill_items)
    taken_positions = []
    GRID[:page_size].times do |t|
      position = t + @starting_position
      if grid_items.any? && grid_items.first.position == position
        @items << grid_items.shift.gridable
        if @items.last.class.name.eql? 'CaseStudy'
          taken_positions << position + (@items.last.block_style == 2 ? 1 : GRID[:row_size])
        end
      elsif fill_items.any? && !taken_positions.include?(position)
        @items << fill_items.shift
      end
    end
  end

  def fetch_grid_items
    GridItem.cached_items(@starting_position)
  end

  def fetch_fill_items(total_grid_items)
    return [] if total_grid_items == GRID[:page_size]

    shots_amount, videos_amount = fill_items_amounts(total_grid_items)
    videos = fetch_videos(videos_amount)

    return videos if shots_amount == 0
    mix_items_into(fetch_shots(shots_amount), videos)
  end

  def fill_items_amounts(items_count)
    shots_left = count_shots_left

    videos_default_amount = items_count > 0 ? 2 : 3
    videos_amount = if shots_left < GRID[:page_size]
      [GRID[:page_size] - items_count - shots_left, videos_default_amount].max
    else
      videos_default_amount
    end

    shots_amount = GRID[:page_size] - items_count - videos_amount
    [shots_amount, videos_amount]
  end

  def mix_items_into(target, items)
    start_position = 0
    items.each do |item|
      end_position = target.size
      insert_position = start_position == end_position ? end_position : rand(start_position...end_position)
      target.insert(insert_position, item)
      start_position = insert_position + 1
    end
    target
  end

  def fetch_videos(amount)
    videos = Video.cached_videos(@starting_position, session[:last_video], amount)
    session[:last_video] = videos.last.timestamp if videos.any?
    videos
  end

  def fetch_shots(amount)
    shots = Shot.cached_shots(@starting_position, session[:last_shot], amount)
    session[:last_shot] = shots.last.timestamp if shots.any?
    shots
  end

  def count_shots_left
    Shot.cached_shots_left(@starting_position, session[:last_shot])
  end

end

app/helpers/admin/grid_helper.rb
module Admin
  module GridHelper

    def calculate_item_position(page_number, item_index)
      page_number * GRID[:page_size] + item_index
    end

    def edit_link_to(path)
      link_to 'Edit', path
    end

    def delete_link_to(path)
      link_to 'Delete', path, data: { confirm: 'Are you sure?' }, method: :delete
    end

    def data_attributes item
      attributes = {
        id: item.id,
        type: item.class.to_s.underscore
      }
      attributes.merge!({ CaseStudy::STYLES.key(item.block_style) => 1 }) if attributes[:type] == 'case_study'
      attributes
    end

    def type_class item
      "type-#{item.class.to_s.underscore}"
    end

  end
end

app/views/admin/grid/_case_study.slim
.item class=type_class(item) data=data_attributes(item)
  .title
    strong =item.class.to_s.titleize
    =item.title
  .item-tooltip
    =edit_link_to(edit_admin_case_study_path(item.id))
    =delete_link_to(admin_case_study_path(item.id))

app/views/admin/grid/_dribbble_fact.slim
.item class=type_class(item) data=data_attributes(item)
  .title
    strong Dribbble Facts

app/views/admin/grid/_facebook_fact.slim
.item class=type_class(item) data=data_attributes(item)
  .title
    strong Facebook Facts

app/views/admin/grid/_grid_page.slim
/ .page data-page=page_number
/   - page.each_with_index do |item, item_index|
/     - item_position = calculate_item_position(page_number, item_index)
/     - if item
/       =render partial: item.class.to_s.underscore, locals: { item: item, position: item_position }
/     - else
/       =render partial: 'empty', locals: { position: item_position, page: page_number, index: item_index }

.page data-page=page_number
  - page.each_with_index do |item, item_index|
    - item_position = calculate_item_position(page_number, item_index)
    .position data-type="position"
      - if item
        =render partial: item.class.to_s.underscore, locals: { item: item, position: item_position }


  / .position
  /   .item.type-tweet
  / .position
  / .position
  / .position
  / .position
  / .position
  / .position
  /   .item.type-case-study data-horizontal="1"
  / .position
  / .position
  /   .item.type-image
  / .position
  / .position
  / .position
  / .position
  /   .item.type-case-study data-vertical="1"
  / .position
  / .position
  / .position
  / .position
  / .position
  / .position
  / .position

app/views/admin/grid/_image.slim
.item class=type_class(item) data=data_attributes(item)
  .title
    strong =item.class.to_s.titleize
  .item-tooltip
    =edit_link_to(edit_admin_image_path(item.id))
    =delete_link_to(admin_image_path(item.id))

app/views/admin/grid/_tweet.slim
.item class=type_class(item) data=data_attributes(item)
  .title
    strong =item.class.to_s.titleize

app/views/admin/grid/index.html.slim
- unless flash[:notice].blank?
  input type="hidden" data-notification="success" value=flash[:notice]

- unless flash[:success].blank?
  input type="hidden" data-notification="success" value=flash[:success]

- unless flash[:error].blank?
  input type="hidden" data-notification="error" value=flash[:error]

javascript:
  var pageSize = #{GRID[:page_size]}, rowSize = #{GRID[:row_size]}, create_urls, sort_urls, remove_urls;

#grid-container data-view="grid"
  #tooltip
  - @pages.each_with_index do |page, page_number|
    =render partial: 'grid_page', locals: { page: page, page_number: page_number }

a#add-page.button Add Page